name: postgrep-conduit
version: "0.1.0"
synopsis: Conduit wrapper around postgrep-core parser
description: Conduit wrapper around postgresp-core parser
category: PostgreSQL
author: David Reaver
maintainer: johndreaver@gmail.com
stability: experimental
license: MIT
license-file: LICENSE.md

github: frontrowed/postgrep

extra-source-files:
  - CHANGELOG.md

dependencies:
  - base >= 4.8 && < 5
  - bytestring
  - conduit
  - conduit-extra
  - postgrep-core
  - resourcet

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - tests
    dependencies:
      - base
      - postgrep-conduit
      - hspec
      - HUnit
  style:
    main: HLint.hs
    source-dirs:
      - tests
    dependencies:
      - base
      - hlint

benchmarks:
  benchmarks:
    dependencies:
      - base
      - postgrep-conduit
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
